### ISSUE TITLE
Completing Tax Forms workflow needs to be updated to reflect `defaults` -> `form` command name change

### ISSUE THREAD

**Issue by zrisher** [brandon-rhodes/luca#4]
In https://luca.readthedocs.org/en/latest/completing-forms.html we see:

> 1. I ask Luca to build an initial, blank version of the form, that lists the default value of each field. I can choose whatever filename I want. I typically start each filename with the year and (if applicable) quarter so that they sort by date when I list the directory.

> `luca defaults us.f941 > 2012-Q1-f941.json`

whereas it should be

`luca form us.f941 2012 > 2012-Q1-f941.json`

And yes, I'm happy to make this change as a PR in the next few days.

**Comment by brandon-rhodes** [comment]
Thanks for pointing this out!
