### ISSUE TITLE
`luca form` usage error message for unrecognized filling year could be more helpful

### ISSUE THREAD

**Issue by zrisher** [brandon-rhodes/luca#6]
If I run 

`luca form us.f1040sa`

I receive 

```
Please specify a particular version of this form with a command like:
   luca form us.f1040sa 2012
```

If I'm a user preparing tax forms, I'm inclined to retry the command with the year I'm filing for:

`luca form us.f1040sa 2014`

But I still receive

```
Please specify a particular version of this form with a command like:
   luca form us.f1040sa 2012
```

Instead, I would expect to receive a us.f1040sa form for 2014 if Luca is able to prepare it, or an error message telling me that Luca does not yet support that year for this tax form.

**Comment by brandon-rhodes** [comment]
That does sound like a bug! I might not have time until after PyCon (May/June), but I will see about getting that fixed.

**Comment by zrisher** [comment]
Sounds good, if I'm able to raise a PR earlier I will.
